import "@/app/globals.css";
import { cn } from "@/lib/utils";
import {
  sirwan_light,
  sirwan_bold,
  sirwan_meduim,
  sirwan_reguler,
} from "@/public/fonts";
import type { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: {
    default: "Shkar Restaurant",
    template: "%s - Shkar Restaurant",
  },
  description:
    "Shkar Restaurant is a modern Restaurant System Generated by Avana Soft Team",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning dir="rtl">
      <body
        className={cn(
          sirwan_light.variable,
          sirwan_bold.variable,
          sirwan_meduim.variable,
          sirwan_reguler.variable,
          "min-h-screen bg-background font-sirwan_meduim",
          {
            "debug-screens": process.env.NODE_ENV === "development",
          }
        )}
      >
        <main>
          {children}

          <Toaster dir="rtl" className="font-sirwan_meduim" />
        </main>
      </body>
    </html>
  );
}
