import "@/app/globals.css";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";
import {
  sirwan_light,
  sirwan_bold,
  sirwan_meduim,
  sirwan_reguler,
} from "@/public/fonts";

export const metadata: Metadata = {
  title: "Sign-in",
  description: "Generated by Avana Soft",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={cn(
        sirwan_light.variable,
        sirwan_bold.variable,
        sirwan_meduim.variable,
        sirwan_reguler.variable,
        "min-h-screen bg-background font-sirwan_reguler",
        "min-h-screen bg-background "
      )}
    >
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}
      </ThemeProvider>
      <Toaster dir="ltr" className="font-sirwan_reguler" />
    </div>
  );
}
